CustomStoreForCarBusiness/CustomStoreForCarBusiness/Controllers/LoadDataController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CustomStoreForCarBusiness.Controllers
{
    [Authorize(Roles = "Admin")]
    public class LoadDataController : Controller
    {
        // Reference to the manager object
        Manager m = new Manager();

        // TODO 16 - Must run methods in this LoadData controller before using the app

        // GET: LoadData
        public ActionResult Index()
        {
            return View();
        }

        // GET: LoadData/Country
        public ActionResult Country()
        {
            if (m.LoadDataCountry())
            {
                ViewBag.Result = "Country data was loaded";
            }
            else
            {
                ViewBag.Result = "(done)";
            }
            return View("result");
        }

        // GET: LoadData/Manufacturer
        public ActionResult Manufacturer()
        {
            ViewBag.Result = m.LoadDataManufacturer()
                ? "Manufacturer data was loaded"
                : "(done)";

            return View("result");
        }

        // GET: LoadData/Vehicle
        public ActionResult Vehicle()
        {
            ViewBag.Result = m.LoadDataVehicle()
                ? "Vehicle data was loaded"
                : "(done)";

            return View("result");
        }

        // GET: LoadData/Remove
        public ActionResult Remove()
        {
            ViewBag.Result = m.RemoveData()
                ? "Data has been removed"
                : "(done)";

            return View("result");
        }

        // GET: LoadData/RemoveDatabase
        public ActionResult RemoveDatabase()
        {
            ViewBag.Result = m.RemoveDatabase()
                ? "Database has been removed"
                : "(done)";

            return View("result");
        }

    }
}

CustomStoreForCarBusiness/CustomStoreForCarBusiness/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - CustomStoreForCarBusiness</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @{
        var userAccount = new CustomStoreForCarBusiness.Controllers.RequestUser(User as System.Security.Claims.ClaimsPrincipal);
    }
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Custom store for car business", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Countries", "Index", "Countries")</li>
                    <li>@Html.ActionLink("Manufacturers", "Index", "Manufacturers")</li>
                    <li>@Html.ActionLink("Vehicles", "Index", "Vehicles")</li>


                    @using System.Security.Claims;
                    @if ((User as ClaimsPrincipal).HasClaim(ClaimTypes.Role, "Admin"))
                    {
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Load data <b class="caret"></b></a>
                            <ul class="dropdown-menu">

                                <li>@Html.ActionLink("Load countries", "Country", "LoadData")</li>
                                <li>@Html.ActionLink("Load manufacturers", "Manufacturer", "LoadData")</li>
                                <li>@Html.ActionLink("Load vehicles", "Vehicle", "LoadData")</li>
                            </ul>
                        </li>
                    }

                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - WEB524 Faculty</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>